// <auto-generated />
using CRM_Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRM_Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260403105937_Step1_Lookups")]
    partial class Step1_Lookups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.ContactType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ContactType", "cust");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Client"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Prospect"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Lead"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Supplier"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.RelationShipType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("RelationShipType", "cust");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Associate"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Banker"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Bookkeeper"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Director"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Lawyer"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Owner"
                        },
                        new
                        {
                            ID = 7,
                            Name = "Professional advisor"
                        },
                        new
                        {
                            ID = 8,
                            Name = "Partner"
                        },
                        new
                        {
                            ID = 9,
                            Name = "Secretary"
                        },
                        new
                        {
                            ID = 10,
                            Name = "Shareholder"
                        },
                        new
                        {
                            ID = 11,
                            Name = "Subsidiary"
                        },
                        new
                        {
                            ID = 12,
                            Name = "Trustee"
                        },
                        new
                        {
                            ID = 13,
                            Name = "Beneficiary"
                        });
                });

            modelBuilder.Entity("CRM_Api.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsChecker")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSuperAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
