// <auto-generated />
using System;
using CRM_Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRM_Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260406061618_MakeAcnNullable")]
    partial class MakeAcnNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addressee")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BranchID")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdDT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int")
                        .HasColumnName("UpdUserID");

                    b.HasKey("Id");

                    b.HasIndex("CustomerID");

                    b.ToTable("Address", "cust");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdDT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int")
                        .HasColumnName("UpdUserID");

                    b.HasKey("Id");

                    b.HasIndex("CustomerID");

                    b.ToTable("Branch", "cust");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.BusinessType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessTypeNM")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BusinessType", "cust");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusinessTypeNM = "Restaurant"
                        },
                        new
                        {
                            Id = 2,
                            BusinessTypeNM = "Massage"
                        },
                        new
                        {
                            Id = 3,
                            BusinessTypeNM = "Education agent"
                        },
                        new
                        {
                            Id = 4,
                            BusinessTypeNM = "Car wash"
                        },
                        new
                        {
                            Id = 5,
                            BusinessTypeNM = "Real estate agent"
                        },
                        new
                        {
                            Id = 6,
                            BusinessTypeNM = "Mortgage broker"
                        },
                        new
                        {
                            Id = 7,
                            BusinessTypeNM = "Cafe"
                        },
                        new
                        {
                            Id = 8,
                            BusinessTypeNM = "Roof restoration"
                        },
                        new
                        {
                            Id = 9,
                            BusinessTypeNM = "Tiler"
                        },
                        new
                        {
                            Id = 10,
                            BusinessTypeNM = "Plumber"
                        },
                        new
                        {
                            Id = 11,
                            BusinessTypeNM = "Electrician"
                        },
                        new
                        {
                            Id = 12,
                            BusinessTypeNM = "Air conditioner mechanic"
                        },
                        new
                        {
                            Id = 13,
                            BusinessTypeNM = "House builder"
                        },
                        new
                        {
                            Id = 14,
                            BusinessTypeNM = "Transport"
                        },
                        new
                        {
                            Id = 15,
                            BusinessTypeNM = "GYM"
                        },
                        new
                        {
                            Id = 16,
                            BusinessTypeNM = "Education institute"
                        },
                        new
                        {
                            Id = 17,
                            BusinessTypeNM = "Tattoo Artist"
                        },
                        new
                        {
                            Id = 18,
                            BusinessTypeNM = "Accounting Firm"
                        },
                        new
                        {
                            Id = 19,
                            BusinessTypeNM = "Panel Beater"
                        },
                        new
                        {
                            Id = 20,
                            BusinessTypeNM = "Painter"
                        });
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.CompanyInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ABVDevisionNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ACNNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ASICCompanyReviewDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountingSoftware")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("AccountingSoftware2")
                        .HasColumnType("bit");

                    b.Property<string>("AnnualAccountsMonth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Background")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassOfClients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<bool?>("FiledbyFirm")
                        .HasColumnType("bit");

                    b.Property<int?>("NoOfEmployee")
                        .HasColumnType("int");

                    b.Property<bool?>("NonResidentClient")
                        .HasColumnType("bit");

                    b.Property<bool?>("SuperContribution")
                        .HasColumnType("bit");

                    b.Property<string>("ToEmailForBASReports")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdDT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int")
                        .HasColumnName("UpdUserID");

                    b.Property<string>("WebSite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerID")
                        .IsUnique();

                    b.ToTable("CustomerCompanyInfo", "cust");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.ContactInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CellPhone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("CellPhonePersonName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email2")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HomePhone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("HomePhonePersonName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Salutation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdDT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int")
                        .HasColumnName("UpdUserID");

                    b.Property<string>("WorkPhone")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("WorkPhonePersonName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerID")
                        .IsUnique();

                    b.ToTable("ContactInfo", "cust");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.ContactType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ContactType", "cust");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Client"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Prospect"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Lead"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Supplier"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Other"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Deregistered"
                        },
                        new
                        {
                            ID = 7,
                            Name = "Moved to other accountants"
                        },
                        new
                        {
                            ID = 8,
                            Name = "Bad clients"
                        });
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ABNNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ACN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("AccountNumber")
                        .HasColumnType("bigint");

                    b.Property<bool?>("AnnualABNTaxReturn")
                        .HasColumnType("bit");

                    b.Property<string>("AnnualAccountsMonth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("AnnualFinancialStatements")
                        .HasColumnType("bit");

                    b.Property<bool?>("AnnualGSTClient")
                        .HasColumnType("bit");

                    b.Property<bool?>("AnnualNonGST")
                        .HasColumnType("bit");

                    b.Property<bool?>("BASA")
                        .HasColumnType("bit");

                    b.Property<bool?>("BASQ")
                        .HasColumnType("bit");

                    b.Property<long?>("BSB")
                        .HasColumnType("bigint");

                    b.Property<string>("BalanceDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("BillingEntity")
                        .HasColumnType("bit");

                    b.Property<string>("BusinessBankAccount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessCreditCardAccount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessLoanAccount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BusinessType")
                        .HasColumnType("int");

                    b.Property<bool?>("ChargeInterest")
                        .HasColumnType("bit");

                    b.Property<bool?>("ChargeMonthlyDisbursement")
                        .HasColumnType("bit");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Client")
                        .HasColumnType("bit");

                    b.Property<string>("ClientFrom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientType")
                        .HasColumnType("int");

                    b.Property<string>("ClientTypeSubcategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("ContactType")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DirectorID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Facsimile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("FinancialStatement")
                        .HasColumnType("bit");

                    b.Property<string>("FirmType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GSTBasis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GSTPeriod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("GSTRegistered")
                        .HasColumnType("bit");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InBusinessSince")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceDeliveryBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsExcluded")
                        .HasColumnType("bit");

                    b.Property<int?>("LastVarifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastVarifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Lodgement")
                        .HasColumnType("bit");

                    b.Property<string>("MailingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manager")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("PAYGWeekly")
                        .HasColumnType("bit");

                    b.Property<string>("Partner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PostNewsLetter")
                        .HasColumnType("bit");

                    b.Property<bool?>("PrepareGST")
                        .HasColumnType("bit");

                    b.Property<bool?>("PrepareGroupCertificates")
                        .HasColumnType("bit");

                    b.Property<string>("Salutation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StaffInCharge")
                        .HasColumnType("int");

                    b.Property<string>("TFNNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxAgent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxReturnType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TradingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TradingStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdDT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int")
                        .HasColumnName("UpdUserID");

                    b.HasKey("Id");

                    b.ToTable("Customers", "cust");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.CustomerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerTypeNM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EntityTypeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdDT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int")
                        .HasColumnName("UpdUserID");

                    b.HasKey("Id");

                    b.ToTable("CustomerType", "cust");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerTypeNM = "Individual",
                            UpdateDateTime = new DateTime(2026, 4, 6, 11, 46, 17, 182, DateTimeKind.Local).AddTicks(3765)
                        },
                        new
                        {
                            Id = 2,
                            CustomerTypeNM = "Company",
                            UpdateDateTime = new DateTime(2026, 4, 6, 11, 46, 17, 183, DateTimeKind.Local).AddTicks(6646)
                        },
                        new
                        {
                            Id = 3,
                            CustomerTypeNM = "Sole Proprietor",
                            UpdateDateTime = new DateTime(2026, 4, 6, 11, 46, 17, 183, DateTimeKind.Local).AddTicks(6661)
                        },
                        new
                        {
                            Id = 4,
                            CustomerTypeNM = "Trust",
                            UpdateDateTime = new DateTime(2026, 4, 6, 11, 46, 17, 183, DateTimeKind.Local).AddTicks(6663)
                        },
                        new
                        {
                            Id = 5,
                            CustomerTypeNM = "AKA",
                            UpdateDateTime = new DateTime(2026, 4, 6, 11, 46, 17, 183, DateTimeKind.Local).AddTicks(6664)
                        },
                        new
                        {
                            Id = 6,
                            CustomerTypeNM = "Partnership",
                            UpdateDateTime = new DateTime(2026, 4, 6, 11, 46, 17, 183, DateTimeKind.Local).AddTicks(6665)
                        },
                        new
                        {
                            Id = 7,
                            CustomerTypeNM = "SMSF",
                            UpdateDateTime = new DateTime(2026, 4, 6, 11, 46, 17, 183, DateTimeKind.Local).AddTicks(6666)
                        },
                        new
                        {
                            Id = 8,
                            CustomerTypeNM = "Staff",
                            UpdateDateTime = new DateTime(2026, 4, 6, 11, 46, 17, 183, DateTimeKind.Local).AddTicks(6666)
                        },
                        new
                        {
                            Id = 9,
                            CustomerTypeNM = "Supplier",
                            UpdateDateTime = new DateTime(2026, 4, 6, 11, 46, 17, 183, DateTimeKind.Local).AddTicks(6667)
                        },
                        new
                        {
                            Id = 10,
                            CustomerTypeNM = "Other",
                            UpdateDateTime = new DateTime(2026, 4, 6, 11, 46, 17, 183, DateTimeKind.Local).AddTicks(6668)
                        });
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.EntityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EntityTypeNM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdDT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int")
                        .HasColumnName("UpdUserID");

                    b.HasKey("Id");

                    b.ToTable("EntityType", "cust");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.IndividualInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("ABNContractor")
                        .HasColumnType("bit");

                    b.Property<bool?>("BASM")
                        .HasColumnType("bit");

                    b.Property<string>("BirthCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ChargeInterest")
                        .HasColumnType("bit");

                    b.Property<bool?>("ChargeMonthlyDisbursement")
                        .HasColumnType("bit");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<bool?>("DASP")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime")
                        .HasColumnName("DateOfBirth");

                    b.Property<DateTime?>("DateOfDeath")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<bool?>("IndividualTaxReturn")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("NonResidentClient")
                        .HasColumnType("bit");

                    b.Property<string>("TFNDivisionNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TitleAbbreviated")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleFull")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdDT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int")
                        .HasColumnName("UpdUserID");

                    b.HasKey("Id");

                    b.HasIndex("CustomerID")
                        .IsUnique();

                    b.ToTable("CustomerIndividualInfo", "cust");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.JobStatusMaster", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool?>("ShowPriority")
                        .HasColumnType("bit");

                    b.Property<string>("StatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("JobStatusMaster", "task");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            StatusName = "Not Yet In"
                        },
                        new
                        {
                            ID = 2,
                            StatusName = "Allocated"
                        },
                        new
                        {
                            ID = 3,
                            StatusName = "Active"
                        },
                        new
                        {
                            ID = 4,
                            StatusName = "Pending"
                        },
                        new
                        {
                            ID = 5,
                            StatusName = "Pre-Interview"
                        },
                        new
                        {
                            ID = 6,
                            StatusName = "Draft"
                        },
                        new
                        {
                            ID = 7,
                            StatusName = "Interviewed"
                        },
                        new
                        {
                            ID = 8,
                            StatusName = "Finalising"
                        },
                        new
                        {
                            ID = 9,
                            StatusName = "Complete"
                        });
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.RelationShipType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("RelationShipType", "cust");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Associate"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Banker"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Bookkeeper"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Director"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Lawyer"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Owner"
                        },
                        new
                        {
                            ID = 7,
                            Name = "Professional advisor"
                        },
                        new
                        {
                            ID = 8,
                            Name = "Partner"
                        },
                        new
                        {
                            ID = 9,
                            Name = "Secretary"
                        },
                        new
                        {
                            ID = 10,
                            Name = "Shareholder"
                        },
                        new
                        {
                            ID = 11,
                            Name = "Subsidiary"
                        },
                        new
                        {
                            ID = 12,
                            Name = "Trustee"
                        },
                        new
                        {
                            ID = 13,
                            Name = "Beneficiary"
                        });
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.SolePropriterInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("ABNContractor")
                        .HasColumnType("bit");

                    b.Property<string>("ABNDivisionNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassOfClients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<bool?>("DASP")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("FiledbyFirm")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("IndividualTaxReturn")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TitleAbbreviated")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleFull")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdDT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int")
                        .HasColumnName("UpdUserID");

                    b.HasKey("Id");

                    b.HasIndex("CustomerID")
                        .IsUnique();

                    b.ToTable("CustomerSolePropriterInfo", "cust");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.TaxAgent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TaxAgent", "cust");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Internal Agent"
                        },
                        new
                        {
                            Id = 2,
                            Name = "External Agent"
                        });
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.TradingStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TradingStatus", "cust");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Active But Not Trading"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Trading Quarterly"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Trading Annually"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Not active & not trading"
                        });
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.TrustInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnnualAccountsMonth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("BASM")
                        .HasColumnType("bit");

                    b.Property<bool?>("ChargeInterest")
                        .HasColumnType("bit");

                    b.Property<bool?>("ChargeMonthlyDisbursement")
                        .HasColumnType("bit");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<bool?>("DASP")
                        .HasColumnType("bit");

                    b.Property<bool?>("FiledbyFirm")
                        .HasColumnType("bit");

                    b.Property<bool?>("NonResidentClient")
                        .HasColumnType("bit");

                    b.Property<bool?>("SuperContribution")
                        .HasColumnType("bit");

                    b.Property<bool?>("SuperHardship")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdDT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int")
                        .HasColumnName("UpdUserID");

                    b.Property<bool?>("WorkerCompensation")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CustomerID")
                        .IsUnique();

                    b.ToTable("CustomerTrustInfo", "cust");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.TypeMaster", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TypeMaster", "task");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ShortCode = "AA",
                            Type = "Annual Accounts"
                        },
                        new
                        {
                            ID = 2,
                            ShortCode = "ASIC",
                            Type = "ASIC Updates"
                        },
                        new
                        {
                            ID = 3,
                            ShortCode = "BAS",
                            Type = "BAS"
                        },
                        new
                        {
                            ID = 4,
                            ShortCode = "BK",
                            Type = "Bookkeeping "
                        },
                        new
                        {
                            ID = 5,
                            ShortCode = "BREG",
                            Type = "Business Registration"
                        },
                        new
                        {
                            ID = 6,
                            ShortCode = "COMP",
                            Type = "Compliance"
                        },
                        new
                        {
                            ID = 7,
                            ShortCode = "FBT",
                            Type = "FBT"
                        },
                        new
                        {
                            ID = 8,
                            ShortCode = "GQ",
                            Type = "General Queries"
                        },
                        new
                        {
                            ID = 9,
                            ShortCode = "FINS",
                            Type = "Financial Statements"
                        },
                        new
                        {
                            ID = 10,
                            ShortCode = "ITR",
                            Type = "Income Tax Return"
                        },
                        new
                        {
                            ID = 11,
                            ShortCode = "IAS",
                            Type = "IAS"
                        },
                        new
                        {
                            ID = 12,
                            ShortCode = "PAYG",
                            Type = "PAYG Summary"
                        },
                        new
                        {
                            ID = 13,
                            ShortCode = "PR",
                            Type = "Payroll"
                        },
                        new
                        {
                            ID = 14,
                            ShortCode = "WC",
                            Type = "Work Cover"
                        },
                        new
                        {
                            ID = 15,
                            ShortCode = "TFN",
                            Type = "TFN Declaration"
                        },
                        new
                        {
                            ID = 16,
                            ShortCode = "STPF",
                            Type = "STP Finalisation"
                        },
                        new
                        {
                            ID = 17,
                            ShortCode = "OTH",
                            Type = "Others"
                        },
                        new
                        {
                            ID = 18,
                            ShortCode = "PR T",
                            Type = "Payroll Tax"
                        },
                        new
                        {
                            ID = 19,
                            ShortCode = "SGC",
                            Type = "Superannuation Guarantee"
                        },
                        new
                        {
                            ID = 20,
                            ShortCode = "TPAR",
                            Type = "Taxable Payments Annual Repor"
                        },
                        new
                        {
                            ID = 21,
                            ShortCode = "REG",
                            Type = "TFN/ABN/PAYG Registration "
                        });
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Operations.Detail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("AssignBy")
                        .HasColumnType("int");

                    b.Property<int?>("AssignTo")
                        .HasColumnType("int");

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerformAction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PeriodEnded")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Priority")
                        .HasColumnType("int");

                    b.Property<int?>("ScheduleID")
                        .HasColumnType("int");

                    b.Property<int?>("Stage")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<int?>("TaskOwner")
                        .HasColumnType("int");

                    b.Property<int>("TypeID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UpdateUserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ScheduleID");

                    b.HasIndex("TypeID");

                    b.ToTable("Detail", "task");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Operations.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DayOfMonth")
                        .HasColumnType("int");

                    b.Property<int?>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int?>("DueDuration")
                        .HasColumnType("int");

                    b.Property<string>("DueMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScheduleDays")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdDT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int")
                        .HasColumnName("UpdUserID");

                    b.HasKey("Id");

                    b.ToTable("Schedule", "task");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Operations.TaskAction", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("ActionMasterID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("AssignDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AssignTo")
                        .HasColumnType("int");

                    b.Property<int?>("ClosedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ClosedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DetailID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("DueDate");

                    b.Property<int?>("DueDuration")
                        .HasColumnType("int");

                    b.Property<string>("DueMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExecutionEndDate")
                        .HasColumnType("date")
                        .HasColumnName("ExecutionEndDate");

                    b.Property<string>("ExecutionEndTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExecutionStartDate")
                        .HasColumnType("date")
                        .HasColumnName("ExecutionStartDate");

                    b.Property<string>("ExecutionStartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsBackground")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("bit");

                    b.Property<int>("NoOfTry")
                        .HasColumnType("int");

                    b.Property<string>("PerformAction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Priority")
                        .HasColumnType("int");

                    b.Property<int?>("ScheduleID")
                        .HasColumnType("int");

                    b.Property<int?>("Stage")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<int?>("TaskOwner")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdDT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int")
                        .HasColumnName("UpdUserID");

                    b.HasKey("ID");

                    b.HasIndex("DetailID");

                    b.HasIndex("ScheduleID");

                    b.ToTable("Action", "task");
                });

            modelBuilder.Entity("CRM_Api.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsChecker")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsSuperAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users", "dbo");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.Address", b =>
                {
                    b.HasOne("CRM_Api.Models.Entities.Customer.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.Branch", b =>
                {
                    b.HasOne("CRM_Api.Models.Entities.Customer.Customer", "Customer")
                        .WithMany("Branches")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.CompanyInfo", b =>
                {
                    b.HasOne("CRM_Api.Models.Entities.Customer.Customer", "Customer")
                        .WithOne("CompanyInfo")
                        .HasForeignKey("CRM_Api.Models.Entities.Customer.CompanyInfo", "CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.ContactInfo", b =>
                {
                    b.HasOne("CRM_Api.Models.Entities.Customer.Customer", "Customer")
                        .WithOne("ContactInfo")
                        .HasForeignKey("CRM_Api.Models.Entities.Customer.ContactInfo", "CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.IndividualInfo", b =>
                {
                    b.HasOne("CRM_Api.Models.Entities.Customer.Customer", "Customer")
                        .WithOne("IndividualInfo")
                        .HasForeignKey("CRM_Api.Models.Entities.Customer.IndividualInfo", "CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.SolePropriterInfo", b =>
                {
                    b.HasOne("CRM_Api.Models.Entities.Customer.Customer", "Customer")
                        .WithOne("SolePropriterInfo")
                        .HasForeignKey("CRM_Api.Models.Entities.Customer.SolePropriterInfo", "CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.TrustInfo", b =>
                {
                    b.HasOne("CRM_Api.Models.Entities.Customer.Customer", "Customer")
                        .WithOne("TrustInfo")
                        .HasForeignKey("CRM_Api.Models.Entities.Customer.TrustInfo", "CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Operations.Detail", b =>
                {
                    b.HasOne("CRM_Api.Models.Entities.Operations.Schedule", "Schedule")
                        .WithMany("Detail")
                        .HasForeignKey("ScheduleID");

                    b.HasOne("CRM_Api.Models.Entities.Customer.TypeMaster", "Type")
                        .WithMany()
                        .HasForeignKey("TypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Operations.TaskAction", b =>
                {
                    b.HasOne("CRM_Api.Models.Entities.Operations.Detail", "Detail")
                        .WithMany("Action")
                        .HasForeignKey("DetailID");

                    b.HasOne("CRM_Api.Models.Entities.Operations.Schedule", "Schedule")
                        .WithMany("Action")
                        .HasForeignKey("ScheduleID");

                    b.Navigation("Detail");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Branches");

                    b.Navigation("CompanyInfo")
                        .IsRequired();

                    b.Navigation("ContactInfo")
                        .IsRequired();

                    b.Navigation("IndividualInfo")
                        .IsRequired();

                    b.Navigation("SolePropriterInfo")
                        .IsRequired();

                    b.Navigation("TrustInfo")
                        .IsRequired();
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Operations.Detail", b =>
                {
                    b.Navigation("Action");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Operations.Schedule", b =>
                {
                    b.Navigation("Action");

                    b.Navigation("Detail");
                });
#pragma warning restore 612, 618
        }
    }
}
