// <auto-generated />
using System;
using CRM_Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CRM_Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260408120826_AddJobTemporaryAssignment")]
    partial class AddJobTemporaryAssignment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Addressee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BranchID")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdDT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int")
                        .HasColumnName("UpdUserID");

                    b.HasKey("Id");

                    b.HasIndex("CustomerID");

                    b.ToTable("Address", "cust");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.BankAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("AccountNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BSB")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BankName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdDT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int")
                        .HasColumnName("UpdUserID");

                    b.HasKey("Id");

                    b.HasIndex("CustomerID");

                    b.ToTable("BankAccount", "cust");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BranchName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdDT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int")
                        .HasColumnName("UpdUserID");

                    b.HasKey("Id");

                    b.HasIndex("CustomerID");

                    b.ToTable("Branch", "cust");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.BusinessType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BusinessTypeNM")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BusinessType", "cust");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusinessTypeNM = "Restaurant"
                        },
                        new
                        {
                            Id = 2,
                            BusinessTypeNM = "Massage"
                        },
                        new
                        {
                            Id = 3,
                            BusinessTypeNM = "Education agent"
                        },
                        new
                        {
                            Id = 4,
                            BusinessTypeNM = "Car wash"
                        },
                        new
                        {
                            Id = 5,
                            BusinessTypeNM = "Real estate agent"
                        },
                        new
                        {
                            Id = 6,
                            BusinessTypeNM = "Mortgage broker"
                        },
                        new
                        {
                            Id = 7,
                            BusinessTypeNM = "Cafe"
                        },
                        new
                        {
                            Id = 8,
                            BusinessTypeNM = "Roof restoration"
                        },
                        new
                        {
                            Id = 9,
                            BusinessTypeNM = "Tiler"
                        },
                        new
                        {
                            Id = 10,
                            BusinessTypeNM = "Plumber"
                        },
                        new
                        {
                            Id = 11,
                            BusinessTypeNM = "Electrician"
                        },
                        new
                        {
                            Id = 12,
                            BusinessTypeNM = "Air conditioner mechanic"
                        },
                        new
                        {
                            Id = 13,
                            BusinessTypeNM = "House builder"
                        },
                        new
                        {
                            Id = 14,
                            BusinessTypeNM = "Transport"
                        },
                        new
                        {
                            Id = 15,
                            BusinessTypeNM = "GYM"
                        },
                        new
                        {
                            Id = 16,
                            BusinessTypeNM = "Education institute"
                        },
                        new
                        {
                            Id = 17,
                            BusinessTypeNM = "Tattoo Artist"
                        },
                        new
                        {
                            Id = 18,
                            BusinessTypeNM = "Accounting Firm"
                        },
                        new
                        {
                            Id = 19,
                            BusinessTypeNM = "Panel Beater"
                        },
                        new
                        {
                            Id = 20,
                            BusinessTypeNM = "Painter"
                        });
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.CompanyInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ABVDevisionNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ACNNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ASICCompanyReviewDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AccountingSoftware")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("AccountingSoftware2")
                        .HasColumnType("bit");

                    b.Property<string>("AnnualAccountsMonth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Background")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassOfClients")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactGroup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<bool?>("FiledbyFirm")
                        .HasColumnType("bit");

                    b.Property<int?>("NoOfEmployee")
                        .HasColumnType("int");

                    b.Property<bool?>("NonResidentClient")
                        .HasColumnType("bit");

                    b.Property<bool?>("SuperContribution")
                        .HasColumnType("bit");

                    b.Property<string>("ToEmailForBASReports")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdDT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int")
                        .HasColumnName("UpdUserID");

                    b.Property<string>("WebSite")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerID")
                        .IsUnique();

                    b.ToTable("CustomerCompanyInfo", "cust");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.ContactInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CellPhone")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("CellPhonePersonName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HomePhone")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("HomePhonePersonName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Salutation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdDT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int")
                        .HasColumnName("UpdUserID");

                    b.Property<string>("WorkPhone")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("WorkPhonePersonName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerID")
                        .IsUnique();

                    b.ToTable("ContactInfo", "cust");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.ContactType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("ContactType", "cust");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Client"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Prospect"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Lead"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Supplier"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Other"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Deregistered"
                        },
                        new
                        {
                            ID = 7,
                            Name = "Moved to other accountants"
                        },
                        new
                        {
                            ID = 8,
                            Name = "Bad clients"
                        });
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ABNNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("AnnualABNTaxReturn")
                        .HasColumnType("bit");

                    b.Property<bool?>("AnnualFinancialStatements")
                        .HasColumnType("bit");

                    b.Property<bool?>("AnnualGSTClient")
                        .HasColumnType("bit");

                    b.Property<bool?>("AnnualNonGST")
                        .HasColumnType("bit");

                    b.Property<bool?>("BASA")
                        .HasColumnType("bit");

                    b.Property<bool?>("BASQ")
                        .HasColumnType("bit");

                    b.Property<string>("BalanceDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("BillingEntity")
                        .HasColumnType("bit");

                    b.Property<int?>("BusinessType")
                        .HasColumnType("int");

                    b.Property<string>("Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Client")
                        .HasColumnType("bit");

                    b.Property<string>("ClientFrom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientType")
                        .HasColumnType("int");

                    b.Property<string>("ClientTypeSubcategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("ContactType")
                        .HasColumnType("int");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Facsimile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("FinancialStatement")
                        .HasColumnType("bit");

                    b.Property<string>("FirmType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GSTBasis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GSTPeriod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("GSTRegistered")
                        .HasColumnType("bit");

                    b.Property<string>("InBusinessSince")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceDeliveryBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsExcluded")
                        .HasColumnType("bit");

                    b.Property<int?>("LastVarifiedBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastVarifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Lodgement")
                        .HasColumnType("bit");

                    b.Property<string>("MailingName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manager")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("PAYGWeekly")
                        .HasColumnType("bit");

                    b.Property<string>("Partner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("PostNewsLetter")
                        .HasColumnType("bit");

                    b.Property<bool?>("PrepareGST")
                        .HasColumnType("bit");

                    b.Property<bool?>("PrepareGroupCertificates")
                        .HasColumnType("bit");

                    b.Property<int?>("StaffInCharge")
                        .HasColumnType("int");

                    b.Property<string>("TFNNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxAgent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxReturnType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TradingName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TradingStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdDT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int")
                        .HasColumnName("UpdUserID");

                    b.HasKey("Id");

                    b.ToTable("Customers", "cust");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.CustomerType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerTypeNM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EntityTypeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdDT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int")
                        .HasColumnName("UpdUserID");

                    b.HasKey("Id");

                    b.ToTable("CustomerType", "cust");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerTypeNM = "Individual",
                            UpdateDateTime = new DateTime(2026, 4, 8, 17, 38, 25, 884, DateTimeKind.Local).AddTicks(2071)
                        },
                        new
                        {
                            Id = 2,
                            CustomerTypeNM = "Company",
                            UpdateDateTime = new DateTime(2026, 4, 8, 17, 38, 25, 885, DateTimeKind.Local).AddTicks(7279)
                        },
                        new
                        {
                            Id = 3,
                            CustomerTypeNM = "Sole Proprietor",
                            UpdateDateTime = new DateTime(2026, 4, 8, 17, 38, 25, 885, DateTimeKind.Local).AddTicks(7296)
                        },
                        new
                        {
                            Id = 4,
                            CustomerTypeNM = "Trust",
                            UpdateDateTime = new DateTime(2026, 4, 8, 17, 38, 25, 885, DateTimeKind.Local).AddTicks(7298)
                        },
                        new
                        {
                            Id = 5,
                            CustomerTypeNM = "AKA",
                            UpdateDateTime = new DateTime(2026, 4, 8, 17, 38, 25, 885, DateTimeKind.Local).AddTicks(7298)
                        },
                        new
                        {
                            Id = 6,
                            CustomerTypeNM = "Partnership",
                            UpdateDateTime = new DateTime(2026, 4, 8, 17, 38, 25, 885, DateTimeKind.Local).AddTicks(7299)
                        },
                        new
                        {
                            Id = 7,
                            CustomerTypeNM = "SMSF",
                            UpdateDateTime = new DateTime(2026, 4, 8, 17, 38, 25, 885, DateTimeKind.Local).AddTicks(7300)
                        },
                        new
                        {
                            Id = 8,
                            CustomerTypeNM = "Staff",
                            UpdateDateTime = new DateTime(2026, 4, 8, 17, 38, 25, 885, DateTimeKind.Local).AddTicks(7301)
                        },
                        new
                        {
                            Id = 9,
                            CustomerTypeNM = "Supplier",
                            UpdateDateTime = new DateTime(2026, 4, 8, 17, 38, 25, 885, DateTimeKind.Local).AddTicks(7302)
                        },
                        new
                        {
                            Id = 10,
                            CustomerTypeNM = "Other",
                            UpdateDateTime = new DateTime(2026, 4, 8, 17, 38, 25, 885, DateTimeKind.Local).AddTicks(7303)
                        });
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.EntityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("EntityTypeNM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdDT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int")
                        .HasColumnName("UpdUserID");

                    b.HasKey("Id");

                    b.ToTable("EntityType", "cust");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.IndividualInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("ABNContractor")
                        .HasColumnType("bit");

                    b.Property<bool?>("BASM")
                        .HasColumnType("bit");

                    b.Property<string>("BirthCountry")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ChargeInterest")
                        .HasColumnType("bit");

                    b.Property<bool?>("ChargeMonthlyDisbursement")
                        .HasColumnType("bit");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<bool?>("DASP")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime")
                        .HasColumnName("DateOfBirth");

                    b.Property<DateTime?>("DateOfDeath")
                        .HasColumnType("datetime2");

                    b.Property<string>("DirectorID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<bool?>("IndividualTaxReturn")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("NonResidentClient")
                        .HasColumnType("bit");

                    b.Property<string>("TFNDivisionNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TitleAbbreviated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleFull")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdDT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int")
                        .HasColumnName("UpdUserID");

                    b.HasKey("Id");

                    b.HasIndex("CustomerID")
                        .IsUnique();

                    b.ToTable("CustomerIndividualInfo", "cust");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.JobStatusMaster", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool?>("ShowPriority")
                        .HasColumnType("bit");

                    b.Property<string>("StatusName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("JobStatusMaster", "task");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            StatusName = "Not Yet In"
                        },
                        new
                        {
                            ID = 2,
                            StatusName = "Active"
                        },
                        new
                        {
                            ID = 3,
                            StatusName = "On Hold"
                        },
                        new
                        {
                            ID = 4,
                            StatusName = "Todo Later"
                        },
                        new
                        {
                            ID = 5,
                            StatusName = "Payment made for invoice"
                        },
                        new
                        {
                            ID = 6,
                            StatusName = "Completed"
                        });
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.RelationShipType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("RelationShipType", "cust");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "Associate"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Banker"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Bookkeeper"
                        },
                        new
                        {
                            ID = 4,
                            Name = "Director"
                        },
                        new
                        {
                            ID = 5,
                            Name = "Lawyer"
                        },
                        new
                        {
                            ID = 6,
                            Name = "Owner"
                        },
                        new
                        {
                            ID = 7,
                            Name = "Professional advisor"
                        },
                        new
                        {
                            ID = 8,
                            Name = "Partner"
                        },
                        new
                        {
                            ID = 9,
                            Name = "Secretary"
                        },
                        new
                        {
                            ID = 10,
                            Name = "Shareholder"
                        },
                        new
                        {
                            ID = 11,
                            Name = "Subsidiary"
                        },
                        new
                        {
                            ID = 12,
                            Name = "Trustee"
                        },
                        new
                        {
                            ID = 13,
                            Name = "Beneficiary"
                        });
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.SolePropriterInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool?>("ABNContractor")
                        .HasColumnType("bit");

                    b.Property<string>("ABNDivisionNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClassOfClients")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<bool?>("DASP")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DirectorID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("FiledbyFirm")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool?>("IndividualTaxReturn")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Title")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TitleAbbreviated")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleFull")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdDT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int")
                        .HasColumnName("UpdUserID");

                    b.HasKey("Id");

                    b.HasIndex("CustomerID")
                        .IsUnique();

                    b.ToTable("CustomerSolePropriterInfo", "cust");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.TaxAgent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TaxAgent", "cust");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Internal Agent"
                        },
                        new
                        {
                            Id = 2,
                            Name = "External Agent"
                        });
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.TradingStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TradingStatus", "cust");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Active But Not Trading"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Trading Quarterly"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Trading Annually"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Not active & not trading"
                        });
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.TrustInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnnualAccountsMonth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("BASM")
                        .HasColumnType("bit");

                    b.Property<bool?>("ChargeInterest")
                        .HasColumnType("bit");

                    b.Property<bool?>("ChargeMonthlyDisbursement")
                        .HasColumnType("bit");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<bool?>("DASP")
                        .HasColumnType("bit");

                    b.Property<bool?>("FiledbyFirm")
                        .HasColumnType("bit");

                    b.Property<bool?>("NonResidentClient")
                        .HasColumnType("bit");

                    b.Property<bool?>("SuperContribution")
                        .HasColumnType("bit");

                    b.Property<bool?>("SuperHardship")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdDT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int")
                        .HasColumnName("UpdUserID");

                    b.Property<bool?>("WorkerCompensation")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CustomerID")
                        .IsUnique();

                    b.ToTable("CustomerTrustInfo", "cust");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.TypeMaster", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TypeMaster", "task");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            ShortCode = "AA",
                            Type = "Annual Accounts"
                        },
                        new
                        {
                            ID = 2,
                            ShortCode = "ASIC",
                            Type = "ASIC Updates"
                        },
                        new
                        {
                            ID = 3,
                            ShortCode = "BAS",
                            Type = "BAS"
                        },
                        new
                        {
                            ID = 4,
                            ShortCode = "BK",
                            Type = "Bookkeeping "
                        },
                        new
                        {
                            ID = 5,
                            ShortCode = "BREG",
                            Type = "Business Registration"
                        },
                        new
                        {
                            ID = 6,
                            ShortCode = "COMP",
                            Type = "Compliance"
                        },
                        new
                        {
                            ID = 7,
                            ShortCode = "FBT",
                            Type = "FBT"
                        },
                        new
                        {
                            ID = 8,
                            ShortCode = "GQ",
                            Type = "General Queries"
                        },
                        new
                        {
                            ID = 9,
                            ShortCode = "FINS",
                            Type = "Financial Statements"
                        },
                        new
                        {
                            ID = 10,
                            ShortCode = "ITR",
                            Type = "Income Tax Return"
                        },
                        new
                        {
                            ID = 11,
                            ShortCode = "IAS",
                            Type = "IAS"
                        },
                        new
                        {
                            ID = 12,
                            ShortCode = "PAYG",
                            Type = "PAYG Summary"
                        },
                        new
                        {
                            ID = 13,
                            ShortCode = "PR",
                            Type = "Payroll"
                        },
                        new
                        {
                            ID = 14,
                            ShortCode = "WC",
                            Type = "Work Cover"
                        },
                        new
                        {
                            ID = 15,
                            ShortCode = "TFN",
                            Type = "TFN Declaration"
                        },
                        new
                        {
                            ID = 16,
                            ShortCode = "STPF",
                            Type = "STP Finalisation"
                        },
                        new
                        {
                            ID = 17,
                            ShortCode = "OTH",
                            Type = "Others"
                        },
                        new
                        {
                            ID = 18,
                            ShortCode = "PR T",
                            Type = "Payroll Tax"
                        },
                        new
                        {
                            ID = 19,
                            ShortCode = "SGC",
                            Type = "Superannuation Guarantee"
                        },
                        new
                        {
                            ID = 20,
                            ShortCode = "TPAR",
                            Type = "Taxable Payments Annual Repor"
                        },
                        new
                        {
                            ID = 21,
                            ShortCode = "REG",
                            Type = "TFN/ABN/PAYG Registration "
                        });
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Operations.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CurrentStage")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DueDateBasis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DueDateDays")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<int>("JobTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("OriginalResponsibleId")
                        .HasColumnType("int");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("int");

                    b.Property<int?>("Period")
                        .HasColumnType("int");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int?>("ResponsibleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TargetEndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TemporaryAssignmentNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("TemporaryAssignmentUntil")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdDT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int")
                        .HasColumnName("UpdUserID");

                    b.HasKey("Id");

                    b.HasIndex("CurrentStage");

                    b.HasIndex("CustomerId");

                    b.HasIndex("JobTypeId");

                    b.ToTable("Job", "task");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Operations.JobComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdDT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int")
                        .HasColumnName("UpdUserID");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobComment", "task");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Operations.JobHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdDT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int")
                        .HasColumnName("UpdUserID");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobHistory", "task");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Operations.JobTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdDT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int")
                        .HasColumnName("UpdUserID");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("JobTask", "task");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Utilities.FileUploadInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileOriginalName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FileServerPath")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<long?>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("FileType")
                        .HasColumnType("int");

                    b.Property<int?>("ProcessResult")
                        .HasColumnType("int");

                    b.Property<string>("ProcessResultLogFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("RecordCount")
                        .HasColumnType("bigint");

                    b.Property<long?>("RecordFailed")
                        .HasColumnType("bigint");

                    b.Property<long?>("RecordProcessed")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdateDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("UpdDT");

                    b.Property<int?>("UpdateUserId")
                        .HasColumnType("int")
                        .HasColumnName("UpdUserID");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UploadedBy")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FileUploadInfo", "file");
                });

            modelBuilder.Entity("CRM_Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Checker",
                            NormalizedName = "CHECKER"
                        },
                        new
                        {
                            Id = 3,
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.Address", b =>
                {
                    b.HasOne("CRM_Api.Models.Entities.Customer.Customer", "Customer")
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.BankAccount", b =>
                {
                    b.HasOne("CRM_Api.Models.Entities.Customer.Customer", "Customer")
                        .WithMany("BankAccounts")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.Branch", b =>
                {
                    b.HasOne("CRM_Api.Models.Entities.Customer.Customer", "Customer")
                        .WithMany("Branches")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.CompanyInfo", b =>
                {
                    b.HasOne("CRM_Api.Models.Entities.Customer.Customer", "Customer")
                        .WithOne("CompanyInfo")
                        .HasForeignKey("CRM_Api.Models.Entities.Customer.CompanyInfo", "CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.ContactInfo", b =>
                {
                    b.HasOne("CRM_Api.Models.Entities.Customer.Customer", "Customer")
                        .WithOne("ContactInfo")
                        .HasForeignKey("CRM_Api.Models.Entities.Customer.ContactInfo", "CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.IndividualInfo", b =>
                {
                    b.HasOne("CRM_Api.Models.Entities.Customer.Customer", "Customer")
                        .WithOne("IndividualInfo")
                        .HasForeignKey("CRM_Api.Models.Entities.Customer.IndividualInfo", "CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.SolePropriterInfo", b =>
                {
                    b.HasOne("CRM_Api.Models.Entities.Customer.Customer", "Customer")
                        .WithOne("SolePropriterInfo")
                        .HasForeignKey("CRM_Api.Models.Entities.Customer.SolePropriterInfo", "CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.TrustInfo", b =>
                {
                    b.HasOne("CRM_Api.Models.Entities.Customer.Customer", "Customer")
                        .WithOne("TrustInfo")
                        .HasForeignKey("CRM_Api.Models.Entities.Customer.TrustInfo", "CustomerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Operations.Job", b =>
                {
                    b.HasOne("CRM_Api.Models.Entities.Customer.JobStatusMaster", "Status")
                        .WithMany()
                        .HasForeignKey("CurrentStage");

                    b.HasOne("CRM_Api.Models.Entities.Customer.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("CRM_Api.Models.Entities.Customer.TypeMaster", "JobType")
                        .WithMany()
                        .HasForeignKey("JobTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("JobType");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Operations.JobComment", b =>
                {
                    b.HasOne("CRM_Api.Models.Entities.Operations.Job", "Job")
                        .WithMany("Comments")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Operations.JobHistory", b =>
                {
                    b.HasOne("CRM_Api.Models.Entities.Operations.Job", "Job")
                        .WithMany("History")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Operations.JobTask", b =>
                {
                    b.HasOne("CRM_Api.Models.Entities.Operations.Job", "Job")
                        .WithMany("Tasks")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("CRM_Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("CRM_Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM_Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("CRM_Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Customer.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("BankAccounts");

                    b.Navigation("Branches");

                    b.Navigation("CompanyInfo");

                    b.Navigation("ContactInfo");

                    b.Navigation("IndividualInfo");

                    b.Navigation("SolePropriterInfo");

                    b.Navigation("TrustInfo");
                });

            modelBuilder.Entity("CRM_Api.Models.Entities.Operations.Job", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("History");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
